# FROM rust:1.65.0-buster
# Unfortunately we can not use the above, as it would compile against a libc
# version (2.28) which is not supported by all gateways yet. Below is the
# source of the Rust image based on Buster, but then using Stretch.

FROM buildpack-deps:stretch

ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    RUST_VERSION=1.68.2

RUN set -eux; \
    dpkgArch="$(dpkg --print-architecture)"; \
    case "${dpkgArch##*-}" in \
        amd64) rustArch='x86_64-unknown-linux-gnu'; rustupSha256='bb31eaf643926b2ee9f4d8d6fc0e2835e03c0a60f34d324048aa194f0b29a71c' ;; \
        armhf) rustArch='armv7-unknown-linux-gnueabihf'; rustupSha256='6626b90205d7fe7058754c8e993b7efd91dedc6833a11a225b296b7c2941194f' ;; \
        arm64) rustArch='aarch64-unknown-linux-gnu'; rustupSha256='4ccaa7de6b8be1569f6b764acc28e84f5eca342f5162cd5c810891bff7ed7f74' ;; \
        i386) rustArch='i686-unknown-linux-gnu'; rustupSha256='34392b53a25c56435b411d3e575b63aab962034dd1409ba405e708610c829607' ;; \
        *) echo >&2 "unsupported architecture: ${dpkgArch}"; exit 1 ;; \
    esac; \
    url="https://static.rust-lang.org/rustup/archive/1.25.2/${rustArch}/rustup-init"; \
    wget "$url"; \
    echo "${rustupSha256} *rustup-init" | sha256sum -c -; \
    chmod +x rustup-init; \
    ./rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION --default-host ${rustArch}; \
    rm rustup-init; \
    chmod -R a+w $RUSTUP_HOME $CARGO_HOME; \
    rustup --version; \
    cargo --version; \
    rustc --version;


ENV PROJECT_PATH=/chirpstack-mqtt-forwarder
RUN mkdir -p $PROJECT_PATH

RUN apt-get update && \
	apt-get install -y \
	make \
	cmake \
	clang-11 \
	libclang-11-dev \
	llvm-dev \
	musl-dev \
	git \
	bash \
	protobuf-compiler \
	libprotobuf-dev \
	jq \
	gcc-arm-linux-gnueabi \
	g++-arm-linux-gnueabi \
	gcc-arm-linux-gnueabihf \
	g++-arm-linux-gnueabihf \
	gcc-aarch64-linux-gnu \
	g++-aarch64-linux-gnu

RUN cargo install cargo-bitbake
RUN cargo install cargo-bloat

# Install musl cross toolchain for mips
# 1.1.24 is the musl version bundled with Rust:
# https://github.com/rust-lang/rust/blob/master/src/ci/docker/scripts/musl.sh#L28
RUN git clone https://github.com/richfelker/musl-cross-make.git /opt/musl-cross-make
RUN echo '\
TARGET = mips-linux-muslsf\n\
OUTPUT = /opt/mips-linux-muslsf\n\
MUSL_VER = 1.1.24\n\
'\
>> /opt/musl-cross-make/config.mak
RUN cd /opt/musl-cross-make && make && make install

# Install opkg-utils
RUN git clone git://git.yoctoproject.org/opkg-utils /opt/opkg-utils && \
	cd /opt/opkg-utils && \
	make install

WORKDIR $PROJECT_PATH
