FROM rust:1.65.0-buster

ENV PROJECT_PATH=/chirpstack-mqtt-forwarder
RUN mkdir -p $PROJECT_PATH

RUN apt-get update && \
	apt-get install -y \
	make \
	cmake \
	clang \
	libclang-dev \
	llvm-dev \
	musl-dev \
	git \
	bash \
	protobuf-compiler \
	jq \
	gcc-arm-linux-gnueabi \
	g++-arm-linux-gnueabi \
	gcc-arm-linux-gnueabihf \
	g++-arm-linux-gnueabihf \
	gcc-aarch64-linux-gnu \
	g++-aarch64-linux-gnu

RUN rustup component add rustfmt clippy
RUN rustup target add mips-unknown-linux-musl
RUN rustup target add armv5te-unknown-linux-gnueabi
RUN rustup target add armv7-unknown-linux-gnueabihf
RUN rustup target add aarch64-unknown-linux-gnu

RUN cargo install cargo-bitbake
RUN cargo install cargo-bloat

# Install musl cross toolchain for mips
# 1.1.24 is the musl version bundled with Rust:
# https://github.com/rust-lang/rust/blob/master/src/ci/docker/scripts/musl.sh#L28
RUN git clone https://github.com/richfelker/musl-cross-make.git /opt/musl-cross-make
RUN echo '\
TARGET = mips-linux-muslsf\n\
OUTPUT = /opt/mips-linux-muslsf\n\
MUSL_VER = 1.1.24\n\
'\
>> /opt/musl-cross-make/config.mak
RUN cd /opt/musl-cross-make && make && make install

# Install opkg-utils
RUN git clone git://git.yoctoproject.org/opkg-utils /opt/opkg-utils && \
	cd /opt/opkg-utils && \
	make install

WORKDIR $PROJECT_PATH
