FROM rust:1.64.0-buster

ENV PROJECT_PATH=/chirpstack-mqtt-forwarder
RUN mkdir -p $PROJECT_PATH

RUN apt-get update && \
	apt-get install -y \
	make \
	cmake \
	clang \
	libclang-dev \
	llvm-dev \
	musl-dev \
	git \
	bash \
	protobuf-compiler \
	jq

RUN rustup component add rustfmt clippy
RUN rustup target add mips-unknown-linux-musl

RUN cargo install cargo-bitbake
RUN cargo install cargo-bloat

# Install musl cross toolchain for mips
# 1.1.24 is the musl version bundled with Rust:
# https://github.com/rust-lang/rust/blob/master/src/ci/docker/scripts/musl.sh#L28
RUN git clone https://github.com/richfelker/musl-cross-make.git /opt/musl-cross-make
RUN echo '\
TARGET = mips-linux-muslsf\n\
OUTPUT = /opt/mips-linux-muslsf\n\
MUSL_VER = 1.1.24\n\
'\
>> /opt/musl-cross-make/config.mak
RUN cd /opt/musl-cross-make && make && make install

RUN echo '\
[target.mips-unknown-linux-musl]\n\
linker = "mips-linux-muslsf-cc"\n\
# https://github.com/rust-lang/rust/issues/80693
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=-s", "-C", "link-arg=-lc", "-C", "link-arg=-lgcc"]\n\
'\
>> /usr/local/cargo/config

# Install opkg-utils
RUN git clone git://git.yoctoproject.org/opkg-utils /opt/opkg-utils && \
	cd /opt/opkg-utils && \
	make install

WORKDIR $PROJECT_PATH
