#!/usr/bin/env bash

# Set config-file permissions
chown -R chirpstack:chirpstack /etc/chirpstack-mqtt-forwarder
chmod 750 /etc/chirpstack-mqtt-forwarder
chmod 640 /etc/chirpstack-mqtt-forwarder/*.toml

#DEBHELPER#
